"""change column genres to genres_old

Revision ID: 25141191d240
Revises: 2912354683c3
Create Date: 2025-09-14 10:52:02.246707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25141191d240'
down_revision = '2912354683c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres_old', sa.String(length=500), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres_old', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres_old')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('genres_old')

    # ### end Alembic commands ###
