"""drop genres_old column

Revision ID: 70110c3dc0a9
Revises: 2cb1322c8889
Create Date: 2025-09-14 11:46:29.672891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70110c3dc0a9'
down_revision = '2cb1322c8889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('genres_old')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres_old')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres_old', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres_old', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
