"""add fields in artist

Revision ID: f6de442ff7ec
Revises: 
Create Date: 2025-09-06 06:28:40.021747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6de442ff7ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('looking_venue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_description', sa.String(), nullable=True))
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('looking_venue')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
